name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - uses: actions/checkout@v3

      - run: make cv.pdf

      - uses: actions/upload-artifact@v3
        with:
          name: cv.pdf
          path: cv.pdf

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: cv.pdf

      - name: Get Release Name
        id: release_name
        run: echo "::set-output name=name::$(git show -s --format=%ad --date=format:%Y-%m ${CIRCLE_SHA1})"

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.release_name.outputs.name }}
          allowUpdates: true
          artifacts: cv.pdf
          gzip: false
